spring:
  application:
    name: yun-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/yunmall
      username: root
      password: 123456

mybatis:
  type-aliases-package: com.yunqi.auth.model.entity
  mapper-locations: classpath:mapper/*Mapper.xml

dubbo:
  scan:
    base-packages: com.yunqi
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
