spring:
  redis:
    host: 43.142.121.125
    port: 6379
    database: 0
  cloud:
    gateway:
      routes:
        - id: auth # 路由规则id，唯一
          uri: lb://yun-auth # 目标服务，lb为负载均衡
          predicates: # 路由规则
            - Path=/auth/** # 以路径作为判断规则
          filters:
            - RewritePath=/auth/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: order
          uri: lb://yun-order
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: login
          uri: lb://yun-auth
          predicates:
            - Path=/login
        - id: logout
          uri: lb://yun-auth
          predicates:
            - Path=/logout

        
knife4j:
  # 聚合 Swagger 文档，参考 https://doc.xiaominfo.com/docs/action/springcloud-gateway 文档
  gateway:
    enabled: true
    routes:
      - name: yun-auth
        service-name: yun-auth
        url: /auth/v3/api-docs
      - name: yun-order
        service-name: yun-order
        url: /order/v3/api-docs