server:
  port: 8081

spring:
  application:
    name: yun-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


dubbo:
  scan:
    base-packages: com.yunqi
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
