spring:
  redis:
    host: 43.142.121.125
    port: 6379
    database: 0
  cloud:
    gateway:
      routes:
        - id: auth # 路由规则id，唯一
          uri: lb://yun-auth # 目标服务，lb为负载均衡
          predicates: # 路由规则
            - Path=/auth/** # 以路径作为判断规则
        - id: order
          uri: lb://yun-order
          predicates:
            - Path=/order/**
        - id: login
          uri: lb://yun-auth
          predicates:
            - Path=/login