server:
  # 需要对外暴露，设置指定端口
  port: 8080
spring:
  application:
    name: yun-gateway
  cloud:
    nacos:
      # 只需要配置一次地址即可
      server-addr: 43.142.121.125:8848
      # 服务发现
      discovery:
        group: DEFAULT_GROUP
    gateway:
      routes:
        - id: auth # 路由规则id，唯一
          uri: lb://yun-auth # 目标服务，lb为负载均衡
          predicates: # 路由规则
            - Path=/auth/** # 以路径作为判断规则
        - id: order
          uri: lb://yun-order
          predicates:
            - Path=/order/**
        - id: login
          uri: lb://yun-auth
          predicates:
            - Path=/login
          filters:
            - PrefixPath=/auth